variables:
  CACHE_FOLDER: $(Pipeline.Workspace)/.cache

stages:
  - stage: prepare
    jobs:
      - job: Update_Cache
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - bash: echo "##vso[task.setvariable variable=CACHE_NAME;]some-value"
            displayName: Set Cache Name
            name: CacheName
          - task: Cache@2
            inputs:
              key: $(CACHE_NAME)
              path: $(CACHE_FOLDER)
              cacheHitVar: CACHE_RESTORED_1
          - bash: |
              set -x
              echo $(CACHE_RESTORED_1)
              mkdir -p $(CACHE_FOLDER)
              ls -laR $(CACHE_FOLDER)
              echo "$(date)" >> $(CACHE_FOLDER)/file1
  - stage: run
    variables:
      CACHE_NAME: $[dependencies.prepare.outputs['Update_Cache.CacheName.CACHE_NAME']
    jobs:
      - job: Check_Cache_1
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - task: Cache@2
            inputs:
              key: $(CACHE_NAME)
              path: $(CACHE_FOLDER)
              cacheHitVar: CACHE_RESTORED_1
          - bash: |
              set -x
              echo $(CACHE_RESTORED_1)
              ls -laR $(CACHE_FOLDER)
              cat $(CACHE_FOLDER)/file1
      - job: Check_Cache_2
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - task: Cache@2
            inputs:
              key: $(CACHE_NAME)
              path: $(CACHE_FOLDER)
              cacheHitVar: CACHE_RESTORED_1
          - bash: |
              set -x
              echo $(CACHE_RESTORED_1)
              ls -laR $(CACHE_FOLDER)
              cat $(CACHE_FOLDER)/file1


